# Generated by Django 4.1.3 on 2022-11-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_author_slug_book_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['second_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='rent',
            name='cost',
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='', upload_to='authors/photos'),
            preserve_default=False,
        ),
    ]
